# Generated by Django 4.2 on 2023-05-09 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('juicios', '0002_historicalmovimientos_iduser_movimientos_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljuicios',
            name='fcFechaDerivacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Fecha del mail de derivación de la causa', null=True, verbose_name='Fecha Derivación'),
        ),
        migrations.AlterField(
            model_name='historicaljuicios',
            name='fcFechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='historicaljuicios',
            name='fcFechaInicio',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de presentación de la demanda', verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='juicios',
            name='fcFechaDerivacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Fecha del mail de derivación de la causa', null=True, verbose_name='Fecha Derivación'),
        ),
        migrations.AlterField(
            model_name='juicios',
            name='fcFechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='juicios',
            name='fcFechaInicio',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de presentación de la demanda', verbose_name='Fecha Inicio'),
        ),
    ]
